version: "1.0"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell 