version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./swagger/swagger.yaml:/usr/share/nginx/html/openapi.yaml
    restart: unless-stopped 