version: '3'
tasks:
  build:
    desc: Сборка бинарника Go
    cmds:
      - go build -o filmhub ./cmd/main.go
  run:
    desc: Запуск приложения локально
    cmds:
      - go run ./cmd/main.go
  vendor:
    desc: Обновить vendor
    cmds:
      - go mod vendor
  tidy:
    desc: Обновить зависимости
    cmds:
      - go mod tidy
  lint:
    desc: Запуск линтера
    cmds:
      - golangci-lint run
  lint:fix:
    desc: Исправить ошибки линтера
    cmds:
      - golangci-lint run --fix
  docker:build:
    desc: Сборка Docker-образа
    cmds:
      - docker build -t filmhub .
  docker:up:
    desc: Запуск docker-compose
    cmds:
      - docker compose -f docker-composer.yml up --build
  docker:down:
    desc: Остановка docker-compose
    cmds:
      - docker compose -f docker-composer.yml down
  migrate:
    desc: Запуск миграций
    cmds:
      - go run ./cmd/migrate/main.go 